# Generated by Django 3.0.6 on 2020-05-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('indexID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Index')),
                ('securityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Security')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('securityID', models.ManyToManyField(to='securitiesManager.Security')),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='securities',
            field=models.ManyToManyField(to='securitiesManager.Security'),
        ),
    ]
