# Generated by Django 3.0.6 on 2020-05-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitiesManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='securities',
            field=models.ManyToManyField(default=None, to='securitiesManager.Security'),
        ),
        migrations.RemoveField(
            model_name='price',
            name='securityID',
        ),
        migrations.AddField(
            model_name='price',
            name='securityID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Security'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='indexID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Index'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='securityID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Security'),
        ),
    ]
