# Generated by Django 3.0.6 on 2020-05-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitiesManager', '0002_auto_20200508_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='securityID',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='indexID',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='securityID',
        ),
        migrations.AddField(
            model_name='price',
            name='security',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Security'),
        ),
        migrations.AddField(
            model_name='weight',
            name='index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Index'),
        ),
        migrations.AddField(
            model_name='weight',
            name='security',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Security'),
        ),
    ]
