# Generated by Django 3.0.6 on 2020-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securitiesManager', '0003_auto_20200508_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
