# Generated by Django 3.0.6 on 2020-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securitiesManager', '0004_auto_20200510_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
