# Generated by Django 3.0.6 on 2020-05-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitiesManager', '0006_auto_20200510_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('index', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Index')),
            ],
        ),
    ]
