# Generated by Django 3.0.6 on 2020-05-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitiesManager', '0008_auto_20200510_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_price',
            name='index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securitiesManager.Index'),
        ),
    ]
